### PR TITLE
Added Elementary OS #230

### PR DESCRIPTION
**Pull request by maxiwolleb**

### CODE REVIEW

**Comment by edent** [comment]
Hi @maxiwolleb, thanks for this. Please can you read the information on https://github.com/edent/SuperTinyIcons#submitting-icons

That will give you the template needed for submitting a valid icon.

**Comment by maxiwolleb** [comment]
Hey, im on it, what background should it be if it is a white icon ? #000 or #fff

**Comment by maxiwolleb** [comment]
Hey I added one with black and white background, sorry for the hassle it is my first contribution :D

**Comment by maxiwolleb** [comment]
Hey ist everything fine now ?

**Pull request closed without merging**
