### PR TITLE
Regenerated Android vector drawables

### LINKED ISSUE #299: Bitbucket and Threema android drawables have invalid attributes
Hello, not sure if this is related to #189 but both Bitbucket and Threema are using an attribute fillColor value of 'url(#a)' which is apparently incompatible

### PR DESCRIPTION
**Pull request by vangyyy**
Recreated all existing android vector drawables and added missing ones that already existed in SVG formats within repository. Fixes #299. I used [this](https://svg2vector.com/) tool, which eliminates problems introduced when converting with [current tool](https://inloop.github.io/svg2android/). It would be a good practice to require this procedure for all newly created icons in the future.

### CODE REVIEW

**Comment by vangyyy** [comment]
Also fixes #189.

**Comment by vangyyy** [comment]
Some icons still seem to be broken. I will try exporting them manually.

**Comment by edent** [comment]
OK. Let me know when they're ready to merge.

**Comment by vangyyy** [comment]
Broken icons:
- [ ] sentry
- [ ] gojek
- [ ] vivino
- [ ] elementaryos
- [ ] rust
- [ ] lastpass
- [ ] calendar
- [ ] sentry
- [ ] redhat
- [ ] open_benches
- [ ] opencores

**Comment by edent** [comment]
This looks great. There are 3 SVGs which look like they've been changed by mistake. If you can revert them, I'll merge the drawables.

Thank you so much for your efforts on this.

**Comment by vangyyy** [comment]
I will look at them, but to generate some android drawables I had to edit couple SVGs, they were so "optimized", that they didn't even work in Inkscape. I will not push them since they seem to work on GitHub, but maybe I will create an issue and a branch with edited files, since I don't feel like messing with optimizing SVGs, they are full size as exported from Inkscape ... your call.

I will add some new icons from master and give you a heads up to merge. Also it would be a good practice to require people at least include XML versions in future PRs. I can maybe write a wiki on this.

**Comment by vangyyy** [comment]
Ok, @edent you can merge this.

**Comment by edent** [comment]
Brilliant stuff - thank you so much. Hopefully this can be useful in andOTP and others.

**Comment by edent** [comment]
@vangyyy could you please work your magic again? We have lots of new icons :-)

**Pull request merged**
