### PR TITLE
ImgBot savings

### PR DESCRIPTION
**Pull request by TPS**
@edent As requested in https://github.com/edent/SuperTinyIcons/issues/478#issuecomment-723659800, this is what [ImgBot](www.ImgBot.net) has distilled. Each of the included files is just a few bytes smaller (mostly whitespace), so I don't know how welcome _that_ is.  Also, I've included a custom `.imgbotconfig` which specifically excludes the `reference` folder.  Let me know what you think! 🙇🏾‍♂️

### CODE REVIEW

**Comment by TPS** [comment]
I'll go through when I can & check for what savings other than whitespace, but why insist on such?  It's much easier to check before/after if _both_ are with/without such, &, @ these sizes, removing whitespace tends to be significant.

**Comment by edent** [comment]
I don't think I was clear enough. A `\n` takes up the same number of bytes as a space. So we use newlines for readability. That also makes it easier to see what a diff has done.

I've just pushed some changes which removed Windows style newlines from some files, and trailing newlines from the end of some files.

I'd be interested to see whether imgbot makes any file savings against these newer, smaller files.

Thanks for your work on this, it is appreciated.

**Comment by TPS** [comment]
Eyeballing it, it looks like it got some missed leading `0.`→`.` & similar.  I'll have ImgBot regenerate against the repo's current iteration asap.

**Comment by TPS** [comment]
Replaced by #485

**Pull request closed without merging**
