### PR TITLE
Add twitter x new logo

### PR DESCRIPTION
**Pull request by 0APOCALYPSE0**

### CODE REVIEW

**Comment by jmb** [comment]
Your submission doesn't follow the guidelines with the following layout and elements required:

```svg
<svg xmlns="http://www.w3.org/2000/svg"
aria-label="..." role="img"
viewBox="0 0 512 512"><rect
width="512" height="512"
fill="#fff"/>...</svg>
```

**Comment by 0APOCALYPSE0** [comment]
Will fix it

**Comment by 0APOCALYPSE0** [comment]
@jmb Hi, Sorry I was busy that is why not able to fix it on time. But now I have updated the SVG and it is following the above guidelines.
Now SVG is able to fit inside a view box of 0 0 512 512.
Could you please review and approve?
Thanks

**Comment by jmb** [comment]
Sorry, some more comments (and I'm not sure I have the permissions to review/approve)...

I don't think there is any need for width, height or version. Also it should follow the guideline template image and be sized to fit the green circle.

**Comment by 0APOCALYPSE0** [comment]
@jmb Adjusted, Now only corners of the icon are touching the yellow circle and I think it is allowed according to the contribution guidelines.
I am also attaching the SVG here

<svg xmlns="http://www.w3.org/2000/svg"
viewBox="0 0 512 512" role="img"
aria-label="X">
<circle fill="#f43" r="256" cx="256" cy="256"/>
  <circle fill="#fd0" r="217.5" cx="256" cy="256"/>
  <circle fill="#5d6" r="192" cx="256" cy="256"/>
<path d="m0 0H512V512H0" fill="#fff" />
  <path transform="translate(108, 103)" style=" stroke:none;fill-rule:nonzero;fill:rgb(0%,0%,0%);fill-opacity:1;" d="M 178.539062 126.964844 L 290.222656 0 L 263.757812 0 L 166.785156 110.242188 L 89.332031 0 L 0 0 L 117.121094 166.703125 L 0 299.847656 L 26.464844 299.847656 L 128.871094 183.425781 L 210.667969 299.847656 L 300 299.847656 L 178.535156 126.964844 Z M 142.292969 168.171875 L 130.425781 151.574219 L 36.003906 19.484375 L 76.652344 19.484375 L 152.851562 126.085938 L 164.71875 142.683594 L 263.769531 281.246094 L 223.117188 281.246094 L 142.292969 168.179688 Z M 142.292969 168.171875 "/>
</svg>

**Comment by jmb** [comment]
Looks good now! 👍🏻

**Review by jmb — CHANGES_REQUESTED** [review]
I think this looks good now, but it could be reduced further by removing the style attribute completely and applying the transform to the coordinates (using: https://yqnn.github.io/svg-path-editor/ can help here!) You could also probably round the coordinates to 1 or 2 decimal places. 😃

**Comment by 0APOCALYPSE0** [comment]
@jmb Thanks for suggesting the life-saving tools for SVG editing :)
I have updated the SVG.

**Comment by jmb** [comment]
I generally open the guideline.svg in Inkscape and then paste the new icon in, adjust things to fit, delete the guideline bits and then use the online tool and a text editor to tweak.

**Review by jmb — APPROVED** [review]
This looks great now! I think @edent will need to merge.

**Comment by Eiim** [comment]
Just hopping in now. It looks like in the updates you broke the guidelines format again. Also, there were a couple more optimizations I wanted to do. How about this code?

```
<svg xmlns="http://www.w3.org/2000/svg"
aria-label="X" role="img"
viewBox="0 0 512 512"><rect
width="512" height="512"
fill="#fff"/><path d="M281.7 234.3 382.2 120h-23.8l-87.3 99.2-69.7-99.2H121l105.4 150L121 389.9h23.8L237 285.1l73.6 104.8H391ZM153.4 137.5H190l168.4 235.6h-36.6Z"/></svg>
```

**Comment by 0APOCALYPSE0** [comment]
@Eiim updated

**Comment by edent** [comment]
Looks good! Please can you regenerate the README then I'll merge.

**Pull request merged**
