### PR TITLE
Add gradle icon

### PR DESCRIPTION
**Pull request by hirakJS**

### CODE REVIEW

**Comment by edent** [comment]
Please can you provide a reference image? You can also shrink the size by simplifying the transform.

**Comment by hirakJS** [comment]
I've update the gradle icon with the new one. Also, I've added the reference image.
Please have a look.

**Comment by hirakJS** [comment]
Is this OK?

**Comment by edent** [comment]
Looks great! Could you do two small things, then I can merge.

1. The nose has a weird bump, can it be smoothed? 
Screenshot_2019-10-09 Add gradle icon by hirakJS · Pull Request #251 · edent SuperTinyIcons

2. Please can you add a white rectangle background like the other icons?

**Comment by hirakJS** [comment]
Changes are done. Also I've added it to README. Please have a look.

**Comment by edent** [comment]
Perfect! Thanks :-)

**Pull request merged**
