### PR TITLE
Adding Playstation Logo

### PR DESCRIPTION
**Pull request by kycilius**
Thank you for your contribution!  Before sending this Pull Request, please confirm the following:

* [x] You have read [the contributing guidelines](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md)
* [x] The icon's size is *under* 1,024 Bytes
* [x] The layout of the SVG looks like this including newlines
```svg
<svg xmlns="http://www.w3.org/2000/svg"
aria-label="..." role="img"
viewBox="0 0 512 512"><path
d="m0 0H512V512H0"
fill="#fff"/> ... </svg>
```

Add Playstation Logo #857

### CODE REVIEW

**Comment by edent** [comment]
Nearly there.

* Fix the formatting so it doesn't have spaces at the start of lines.
* Name should just be "PlayStation" - no need for the word "logo".
* Looking on the official site, I think the colour should be `#0070d1`

**Comment by kycilius** [comment]
Thanks for the review @edent 
I hope this will be perfect.

**Comment by kycilius** [comment]
@edent is it good

**Comment by edent** [comment]
@kycilius Almost!

Yours starts like this:

```svg
<svg xmlns="http://www.w3.org/2000/svg"
  aria-label="PlayStation" role="img"
  viewBox="0 0 512 512">
```

Can you see how that's different from all the other images in the repo?

**Pull request merged**
