### PR TITLE
Run tests on push with GitHub Actions

### PR DESCRIPTION
**Pull request by MalloryA**
You've got a test suite. You may as well use it.

You may need to fiddle with some GitHub Actions settings to have it run on PRs from other contributors. You can see on my copy of the repo that the tests are failing right now: https://github.com/MalloryA/SuperTinyIcons/actions/runs/3704842461/jobs/6277975021

### CODE REVIEW

**Comment by Eiim** [comment]
This seems like a good idea to me, but I'll leave it up to @edent

**Comment by MalloryA** [comment]
I fixed a few icons which were failing tests due to having a trailing newline added, the size in the README being wrong, and two with validation errors.

Tests are now passing:

https://github.com/MalloryA/SuperTinyIcons/actions/runs/3762302546/jobs/6394871907

**Comment by edent** [comment]
Hi - sorry for the delay, I've been on holiday.

Could you explain a bit more about what tests it actually runs? There doesn't seem to be any in the PR.

(Note, I am *very* jetlagged - so sorry if I've missed something.)

**Comment by MalloryA** [comment]
> There doesn't seem to be any in the PR.

The tests have been in this repo for 2 years. I just added a GitHub Actions config file so that GitHub will run the tests (and I fixed a couple of tests).

They perform the following checks for each SVG:

```
  atom.svg
   18 / 338
    ✔ should exists
    ✔ should be under 1KB
    ✔ should be validated by the w3c validator (125ms)
    ✔ should match readme size
```

I rebased against `master` to fix a merge conflict, but the [tests are failing now](https://github.com/MalloryA/SuperTinyIcons/actions/runs/3812438885/jobs/6485645921) due to one icon (added after this PR was created) failing validation:

```
  1) expressionengine.svg
       should be validated by the w3c validator:
     AssertionError: expected ':6.446-6.513: error: Attribute “trans…' to be empty
```

**Comment by edent** [comment]
> The tests have been in this repo for 2 years.

😳

**Pull request merged**
