### PR TITLE
Added Orcid Icon

### PR DESCRIPTION
**Pull request by agungjsp**
- [x] New file
- [x] Edit Readme
- [x] Add reference image
- [x] Edit reference page
- [x] (optional) Android Image

#229

### CODE REVIEW

**Comment by edent** [comment]
Thank you so much for this. I think the icon needs a little more work. At the moment, it seems squished in the corner:
Screenshot_2019-09-30 Added Orcid Icon by agungjsp · Pull Request #233 · edent SuperTinyIcons

**Comment by agungjsp** [comment]
I just committed, is everything fine?

**Comment by edent** [comment]
It is *very* close! Take a look at some of the other icons. We use this template:

```
<svg
xmlns="http://www.w3.org/2000/svg"
aria-label="..." role="img"
viewBox="0 0 512 512"><rect
width="512" height="512"
rx="15%"
fill="#fff"/> ...
</svg>
```

So, if you can fix the viewbox to be the same as the others, I can accept it :-)

**Comment by agungjsp** [comment]
I'm sorry, the SVG won't work properly when I use the template, so SVG will automatically be like this:



If I change the ViewBox and width to ```256```, it might works.

**Pull request closed without merging**
