### PR TITLE
Humble Bundle icon

### PR DESCRIPTION
**Pull request by The24thDS**
This should take care of a part of #362

### CODE REVIEW

**Comment by edent** [comment]
That's *really* close, but not quite right. If you set `rx="50%"` you'll see that the red stick goes outside the bounds. 
A broken image
Take a look at the guideline SVG in the Contributing file - that should help.

**Comment by The24thDS** [comment]
Now it should be fine :)

**Comment by admvx** [comment]
Thanks for the update @The24thDS :) I think the centering is better now, but the icon is too large with respect to the guide SVG:

image

Plus one naming issue from the contributing doc:
>Filename should be `nameofservice.svg` - all in lower-case. If a special character must be used, please replace it with an underscore (not a dot nor a dash).

**Comment by The24thDS** [comment]
You are right. I will fix these as soon as I have some free time.

**Comment by The24thDS** [comment]
Can you check it now @edent?

**Comment by edent** [comment]
Lovely stuff. Well done!

**Pull request merged**
