### PR TITLE
Added McDonald's logo and updated README.md

### PR DESCRIPTION
**Pull request by aditi-manthri**
I have done the following

* [x] You have read [the contributing guidelines](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md)
* [x] The icon's size is *under* 1,024 Bytes
* [x] The layout of the SVG looks like this including newlines
```svg
<svg xmlns="http://www.w3.org/2000/svg"
aria-label="..." role="img"
viewBox="0 0 512 512"><path
d="m0 0H512V512H0"
fill="#fff"/> ... </svg>
```

### CODE REVIEW

**Comment by edent** [comment]
This is great - thanks! Could you please add a reference image / URL then update the README?

**Comment by aditi-manthri** [comment]
> This is great - thanks! Could you please add a reference image / URL then update the README?

Will do, sure thing!

**Comment by edent** [comment]
As per https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md 

To update the README, run `python3 update_readme.py`

**Comment by aditi-manthri** [comment]
Hey, is this fine?

**Comment by edent** [comment]
Excellent. Thank you.

**Pull request merged**
