### PR TITLE
Filestash SVG

### PR DESCRIPTION
**Pull request by sharansukesh1003**
Filestash SVG Added

### CODE REVIEW

**Comment by edent** [comment]
Please follow the guide at https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md

Once you do, I'll accept and you can get your Hacktoberfest points :-)

**Comment by sharansukesh1003** [comment]
Can you please tell me the changes I need to make, I will work on it. Like is it the file size or is it touching the red zone.

**Comment by edent** [comment]
Here's the Amazon logo:

```
<svg xmlns="http://www.w3.org/2000/svg"
aria-label="Amazon" role="img"
viewBox="0 0 512 512"><rect
width="512" height="512"
rx="15%"
fill="#f90"/><path
fill="#fff"
d="M283 187c-62 2-121 19-121 81 0 43 26 64 61 64 31 0 51-12 68-30 8 11 10 16 24 27 3 2 8 2 10-1l31-27c4-3 2-8 0-10-7-11-15-19-15-39v-64c0-27 2-52-18-70-17-16-38-20-62-21-53-1-88 28-93 62-1 6 4 9 7 9l37 5c6 1 9-4 10-8 6-22 29-28 43-23 20 6 18 29 18 45zm-36 105c-15 0-25-13-25-30 1-36 29-42 61-42v18c0 32-17 54-36 54zm168 106c13-11 26-38 25-57 0-7-1-8-8-10-13-4-46-5-62 10-3 3-2 5 1 5 11-2 45-6 50 2 4 7-8 35-12 47-2 5 2 6 6 3zM58 342c96 91 247 94 345 25 7-4 0-12-6-9a376 376 0 0 1-335-21c-4-3-8 2-4 5z"/></svg>
```
See how it is different to yours?

Yours looks like:
```
<svg width="500" height="500" viewBox="0 0 500 500" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M249.819 82.022C188.891 82.03 139.454 131.443 139.274 192.511C139.466 192.503 139.658 192.497 139.849 192.49C202.846 191.931 250.118 248.593 251.069 294.264C249.708 247.746 299.875 193.308 360.366 192.539C360.202 131.458 310.758 82.0279 249.818 82.022H249.819ZM360.366 192.539L360.376 192.839C283.823 196.305 250.515 260.843 250.832 294.035C251.44 357.583 217.596 413.514 134.414 413.863L361.771 413.013C422.832 413.014 472.331 364.506 472.331 303.304C472.33 242.102 422.831 192.489 361.771 192.49C361.303 192.503 360.835 192.52 360.367 192.539L360.366 192.539ZM250.74 294.038C249.164 250.294 208.438 193.247 139.259 192.839L139.274 192.511C78.4479 192.828 29.3017 242.335 29.2896 303.304C29.289 364.506 78.2359 414.074 133.815 413.844C232.42 413.436 252.317 337.782 250.74 294.038Z" stroke="#F2F3F5" stroke-width="35"/>
</svg>
```

Your width, height, and viewbox are the wrong size. You don't have a background colour. There's no aria-label. And you haven't optimised the path.

**Comment by sharansukesh1003** [comment]
Okay got it will work on this thanks!

**Comment by sharansukesh1003** [comment]
I did all the changes, this is my first time open source contribution. Sorry for the inconvenience.

**Comment by sharansukesh1003** [comment]
Hi, I have made the changes can you have a look at it, I want the points for hacktober so bad xD.

**Comment by sharansukesh1003** [comment]
Hi, @edent can you please review my PR, if everything is correct please merge. I wanted this for  Hacktober 2022 🙂.

**Comment by sharansukesh1003** [comment]
Hi, can you please verify the latest commit @edent @Eiim. Thanks!

**Comment by Eiim** [comment]
It doesn't look like this would fit in the green circle in the guideline image.

**Comment by Eiim** [comment]
Additionally, the path still isn't really optimized (lots of unnecessary decimals) and the newlines don't really follow the reference (there should be newlines breaking up the `<svg>` and `rect` tags).

**Comment by sharansukesh1003** [comment]
> Additionally, the path still isn't really optimized (lots of unnecessary decimals) and the newlines don't really follow the reference (there should be newlines breaking up the `<svg>` and `rect` tags).

How can I optimize the path? I am unaware of how to do it.

**Comment by Eiim** [comment]
As linked in the README, https://yqnn.github.io/svg-path-editor/ is an excellent and powerful tool, and it's the main one I use for path optimization.

**Comment by sharansukesh1003** [comment]
> As linked in the README, https://yqnn.github.io/svg-path-editor/ is an excellent and powerful tool, and it's the main one I use for path optimization.

@Eiim I made the changes, have a look. Thanks!

**Comment by sharansukesh1003** [comment]
Why is it made invalid? What went wrong from my side?

**Comment by edent** [comment]
Please follow the guide at https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md

**Pull request closed without merging**
