### PR TITLE
Vegetarian logo updated Fixes-#813

### LINKED ISSUE #813: Vegetarian Logo Update
The current vegetarian logo is outdated. It needs to be replaced with this - https://commons.wikimedia.org/wiki/Category:V-Label#/media/File:Vegetarian-mark.svg - in a green circle.

### PR DESCRIPTION
**Pull request by pranavkangale5**
-Fixes #813 

- Preview of the updated logo:- 

Screenshot 2024-10-01 233020

### CODE REVIEW

**Comment by Eiim** [comment]
Be sure to following the [CONTRIBUTING.md](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md) guidelines. Most importantly, the format of your SVG is off and the icon is larger 1,024 bytes. But I think those are quite fixable!

**Comment by pranavkangale5** [comment]
> Be sure to following the [CONTRIBUTING.md](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md) guidelines. Most importantly, the format of your SVG is off and the icon is larger 1,024 bytes. But I think those are quite fixable!

Can you please tell me how can I fix that?

**Comment by Eiim** [comment]
You will need to edit your SVG file so that it follows the specified format, which includes exactly what your first four lines should look like. You don't need any RDF metadata or SVG comments that you've included. The final file size should be under 1,024 bytes. If you have it in the right format but can't quite get it under the 1024 threshold, we may be able to help simplify the SVG code.

**Comment by edent** [comment]
Fixed in https://github.com/edent/SuperTinyIcons/commit/4a370ee39d442391dcde287a1103c7a7aafecb5f

**Pull request closed without merging**
