### PR TITLE
Create xmpp.svg

### PR DESCRIPTION
**Pull request by wuxmedia**
adding first draft, looks ok and in under 1023 :D

### CODE REVIEW

**Comment by edent** [comment]
That's a great start, thanks! Please can you follow the template in https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md to make sure it is 512x512. Then we can merge it.

**Comment by wuxmedia** [comment]
yeah, that's where it goes all wrong. buggered up your readme as well :/

**Comment by wuxmedia** [comment]
jeez this i one way of learning github, how the hell do I refresh the file?

**Comment by edent** [comment]
Haha! Yeah, GitHub is "fun". You should be able to push another commit to your branch. If that doesn't work, delete everything and start again :-)

**Pull request closed without merging**
