### PR TITLE
Added a graphql svg icon which is around of 658 bytes . 

### PR DESCRIPTION
**Pull request by Akrati00**
Thank you for your contribution!  Before sending this Pull Request, please confirm the following:

* [x] You have read [the contributing guidelines](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md)
* [x] The icon's size is *under* 1,024 Bytes
* [ ] The layout of the SVG looks like this including newlines
```svg
<svg xmlns="http://www.w3.org/2000/svg"
aria-label="..." role="img"
viewBox="0 0 512 512"><path
d="m0 0H512V512H0"
fill="#fff"/> ... </svg>
```

If you have done the above, please send the Pull Request.

### CODE REVIEW

**Comment by edent** [comment]
@Akrati00 did you read the Contributing guidelines?

**Comment by Akrati00** [comment]
@edent yes

**Comment by Akrati00** [comment]
> @Akrati00 did you read the Contributing guidelines?

yes

**Comment by edent** [comment]
You ticked a Box saying it had this layout

```
<svg xmlns="http://www.w3.org/2000/svg"
aria-label="..." role="img"
viewBox="0 0 512 512"><path
d="m0 0H512V512H0"
fill="#fff"/> ... </svg>
```

Does it have that layout? Can you see how your submission differs from the guidelines?

**Comment by edent** [comment]
@Akrati00 I need you to actually read all of https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md

It has all the information you need.

**Comment by Akrati00** [comment]
> @Akrati00 I need you to actually read all of https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md
> 
> It has all the information you need.

okay sure

**Comment by edent** [comment]
You need to read https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md#guidelines

Your icon must fit in the green circle.

**Comment by edent** [comment]
@Akrati00 Please do not push commits until you are ready. Additionally, I recommend *not* using AI to try and generate this. You can ask questions if you're having trouble.

**Comment by Akrati00** [comment]
> @Akrati00 Please do not push commits until you are ready. Additionally, I recommend _not_ using AI to try and generate this. You can ask questions if you're having trouble.

okay thanks... I will try in another branch...

**Pull request closed without merging**
