### PR TITLE
added Taiga.io icon

### PR DESCRIPTION
**Pull request by wuxmedia**
per #258
what happens with all the other commits on this PR?

### CODE REVIEW

**Comment by wuxmedia** [comment]
github is really annoying. i'm going to bed :/

**Comment by edent** [comment]
> github is really annoying. i'm going to bed :/

I know your pain! The easiest thing to do, I find, it to create a separate branch for each pull request.

`git checkout -b My-Branch-Name`

Good luck!

**Comment by edent** [comment]
> github is really annoying. i'm going to bed :/

I know your pain! The easiest thing to do, I find, it to create a separate branch for each pull request.

`git checkout -b My-Branch-Name`

Good luck!

**Comment by wuxmedia** [comment]
Mental, so -- blow away my fork then fork back to your current master. then branch (which makes sense) everytime _before_ I add an icon?

**Pull request closed without merging**
