### PR TITLE
Added mdBook/GitBook/MkDocs icons #793

### PR DESCRIPTION
**Pull request by HemanthTigga**
Thank you for your contribution!  Before sending this Pull Request, please confirm the following:

* [x] You have read [the contributing guidelines](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md)
* [x] The icon's size is *under* 1,024 Bytes
* [x] The layout of the SVG looks like this including newlines
```svg
<svg xmlns="http://www.w3.org/2000/svg"
aria-label="..." role="img"
viewBox="0 0 512 512"><path
d="m0 0H512V512H0"
fill="#fff"/> ... </svg>
```

If you have done the above, please send the Pull Request.

### CODE REVIEW

**Comment by HemanthTigga** [comment]
please review

**Comment by edent** [comment]
@HemanthTigga You've ticked the box that says the images are under 1KB. But two of the images are much larger. Why is that?

Additionally, they don't look like all the other icons, do they?

Please correct them. Ask questions if you need to.

**Comment by HemanthTigga** [comment]
How do i scale down viewbox because if i use 0 0 512 512, the image just overflows. How do i fix it?

**Comment by edent** [comment]
You can try using [Yann Armelin's SVG Path Editor](https://yqnn.github.io/svg-path-editor/), [svgo](https://github.com/svg/svgo), and [svgcleaner](https://github.com/RazrFalcon/svgcleaner).

**Comment by HemanthTigga** [comment]
Thanks! I'll try these right away.

**Comment by HemanthTigga** [comment]
updated the viewbox of all three files

**Comment by edent** [comment]
@HemanthTigga Have you read the Contributing guide?

* gitBook is 1.15 KB
* mdBook won't fit in the guidelines
* mkDocs is 2.05 KB and doesn't look like their official logo

**Comment by HemanthTigga** [comment]
I tried reducing the size but that's as far as I could go.

**Comment by edent** [comment]
Take a look at the viewbox of gitBook - it's set to 6500! Reduce that and scale the image. That should help.

Perhaps delete the others and come back when you understand a bit more about what you're doing?

**Comment by edent** [comment]
@HemanthTigga Any updates?

**Pull request closed without merging**
