### PR TITLE
Patch round path's values + perceptualdiff 27 icons

### PR DESCRIPTION
**Pull request by 3l3gant-cod3s**
1. extract paths' data: xmlstarlet sel -t -m '//@d' -o '"' -v '.' -o '"' -n $f (xidel, xmllint --xpath […] could the job too)
2. rounds path's values: svg_path_transform --ndig 0 <<< "path-data" (pip install svg-path-transform)
3. search-replace old paths with new paths with sed, xmlstarlet ed […]
4. compact paths: scour --indent=none --no-line-breaks --strip-xml-space --enable-id-stripping --strip-xml-prolog --enable-comment-stripping --remove-descriptive-elements "$new" -o "$new_optimised"
5. remove newlines except in header: sed / geany (editor)
6. compare sizes of old and new SVGs: wc -c
7. keep better ones ;o)
8. export to old and new SVGs to PNGs: for f in *.svg; do inkscape $f -b "#ffffff" -z -C  -w 512 -h 512 -o png/${f/\.svg/}.png; done
9. compare “visually”: perceptualdiff --threshold 266 $old $new_optimised (266 = 1 ‰ of 512×512 pixels)
10. manually inspect files over the threshold and keep them if the difference is less than 1 pixel wide i. ex. 1 pixel offset of whole icon.

### CODE REVIEW

**Comment by 3l3gant-cod3s** [comment]
@Eiim – in the [ Files changed (28) ] Tab above, I load* a (large) diff of the Readme.md with the 27 new sizes… ???
* cf Load diff / Large diffs are not rendered by default

**Comment by Eiim** [comment]
Huh, I missed that, nevermind

**Comment by edent** [comment]
LGTM. Looks like there are a few conflicts to resolve. My fault for not keeping up to date with the repo. Would you mind fixing and I'll merge. Ta!

**Comment by Eiim** [comment]
I resolved the conflicts and merged. I noticed some of the SVG conflicts weren't reflected in the README conflicts, so I'm curious if there might be some out-of-date sizes in the README. Might be worth running a script to check them.

**Pull request merged**
