### PR TITLE
 vscommunity svg

### PR DESCRIPTION
**Pull request by MAsad92**
Thank you for your contribution!  Before sending this Pull Request, please confirm the following:

* [ ] You have read [the contributing guidelines](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md)
* [ ] The icon's size is *under* 1,024 Bytes
* [ ] The layout of the SVG looks like this including newlines
```svg
<svg xmlns="http://www.w3.org/2000/svg"
aria-label="..." role="img"
viewBox="0 0 512 512"><path
d="m0 0H512V512H0"
fill="#fff"/> ... </svg>
```

If you have done the above, please send the Pull Request.

### CODE REVIEW

**Comment by edent** [comment]
@MAsad92 why did you check those boxes? You haven't read the guidelines. The code is over 1k. The layout is wrong.

Is this Hacktoberfest spam?

**Comment by MAsad92** [comment]
Sorry about that!

**Comment by edent** [comment]
@MAsad92 are you going to fix it?

**Comment by MAsad92** [comment]
Yes sure i'll do

**Pull request closed without merging**
