### PR TITLE
Add Deezer Logo

### LINKED ISSUE #281: Add Deezer podcast logo
## The icon I want is:

* Name: Deezer 
* URL: https://www.deezer.com
* Link to icon: https://deezerbrand.com/d/9wmMErzrRuiH/brand-elements

* Vector version of the logo:
* Official style guide or brand guide: https://developers.deezer.com/guidelines/logo

### PR DESCRIPTION
**Pull request by matheusagcosta**
Closes #281

### CODE REVIEW

**Comment by edent** [comment]
Please follow the guidelines at https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md

**Comment by matheusagcosta** [comment]
@edent If the problem was the whitespace that is fixed. Otherwise just tell me what's wrong cause I was following the guidelines.

**Comment by edent** [comment]
All icons must be under 1,024 bytes. Look at all the others - they're square icons.

Your submitted icon is too large and the wrong dimensions.

**Comment by matheusagcosta** [comment]
@edent that's impossible for Deezer considering their logo has a lot of gradient. Should I replace by the black and white version instead?

**Comment by edent** [comment]
Take a look at all the other logos in this repo for inspiration. I'm confident you can get the icon down to that size.

**Comment by matheusagcosta** [comment]
@edent I've tried many different ways and even using the symbol version only that's the minimum I can get. Any suggestions?

image

**Comment by edent** [comment]
Closed by #301

**Pull request closed without merging**
