### PR TITLE
Invert colors

### PR DESCRIPTION
**Pull request by fileformat**

### CODE REVIEW

**Comment by edent** [comment]
Thanks! I'm still thinking about this. I guess I'm not sure why these particular icons *should* have a coloured background - other than personal preference.

**Comment by fileformat** [comment]
No worries, I'm not offended.  I just want to contribute upstream & not be a mooch.  I'm using them on my site, where I have a separate versions with an "icon" flavor (for light backgrounds) and a "tile" version (for dark backrounds or standalone buttons).

I made a [compare page](http://www.vectorlogo.zone/util/tile-vs-supertiny.html) so you can see the difference between your originals & what I have tweaked.  

Do you want my versions of Slack or Baidu?

**Comment by arturoacevedob** [comment]
I think this is a good discussion to have. Icons need a certain design consistency and following brand guidelines doesn't guaranty that.

**Comment by edent** [comment]
OK :-)  @fileformat please can you update the README with the new file sizes, then I'll merge.

**Comment by edent** [comment]
Still interested in this. Just needs the README to be updated, if someone wants to pick that up.

**Pull request closed without merging**
