### PR TITLE
Added Open Street Map Logo

### PR DESCRIPTION
**Pull request by RiyaBhaskar12**

### CODE REVIEW

**Comment by RiyaBhaskar12** [comment]
I've added a  new logo for reference and svg.

**Comment by edent** [comment]
Hi Riya, I think there's a mistake. The SVG appears to be of Pinterest rather than OSM?

**Comment by RiyaBhaskar12** [comment]
icon corrected

**Comment by RiyaBhaskar12** [comment]
please give hacktoberfest accepted title

**Comment by edent** [comment]
Please follow https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md

**Pull request closed without merging**
