### PR TITLE
Vegetarian Logo Update #813

### LINKED ISSUE #813: Vegetarian Logo Update
The current vegetarian logo is outdated. It needs to be replaced with this - https://commons.wikimedia.org/wiki/Category:V-Label#/media/File:Vegetarian-mark.svg - in a green circle.

### PR DESCRIPTION
**Pull request by QaisarMoin**
Fixes #813
Preview of the updated logo:- 

Screenshot 2024-10-02 at 1 58 51 AM

### CODE REVIEW

**Comment by Eiim** [comment]
Please consult [CONTRIBUTING.md](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md). This SVG is over 1,024 bytes and it doesn't follow this required format:
```svg
<svg xmlns="http://www.w3.org/2000/svg"
aria-label="..." role="img"
viewBox="0 0 512 512"><path
d="m0 0H512V512H0"
fill="#fff"/> ... </svg>
```
Additionally, you base64-embedded another SVG inside this SVG? I can't think of any good reason to do this, and it's definitely part of why the file size is so large.

**Comment by edent** [comment]
Fixed in https://github.com/edent/SuperTinyIcons/commit/4a370ee39d442391dcde287a1103c7a7aafecb5f

**Comment by QaisarMoin** [comment]
sir can i ask you why you labeled me spam

**Comment by edent** [comment]
@QaisarMoin You didn't follow the guide in [CONTRIBUTING.md](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md).  You appear to be spamming Hacktoberfest project with useless Pull Requests.

This is not the way to become a coder.

Take your time. Read the documentation. Ask questions.

**Comment by QaisarMoin** [comment]
> You appear to be spamming Hacktoberfest project with useless Pull Requests.

  Ok sir , I am very sorry  for any mistakes in my contribution. I am newbie on GitHub, and this is my first time participating in Hacktoberfest and contributing to open source. Kindly remove the spam tag, as I'm still learning. Thank you for understanding!"

**Pull request closed without merging**
