### PR TITLE
Update rss.svg

### PR DESCRIPTION
**Pull request by 17jiangz1**
Optimised -a few bytes

### CODE REVIEW

**Comment by edent** [comment]
The circle needs to be filled.

**Comment by 17jiangz1** [comment]
The circle appears to be filled in Chrome, Opera, and Safari. It seems to be a quirk with Firefox... The same issue is present in Instagram's flash circle, albeit less visible.
image

**Comment by 17jiangz1** [comment]
Seems to be a bug in Firefox:
https://bugzilla.mozilla.org/show_bug.cgi?id=896248

**Comment by edent** [comment]
Yes, I think the easiest thing to do is move the circle outside of the group. Then fill it.

**Pull request merged**
