### PR TITLE
Add captions for easy searching

### PR DESCRIPTION
**Pull request by florisluiten**
As said in issue #69, captions allow for searching a specific icon. I've implemented the captions in the README.md as well as in the radius.html. The latter uses the aria-label of the SVG, so icon builders do not need to do anything special for that.

### CODE REVIEW

**Comment by edent** [comment]
Wow! That's fantastic. Thank you so much 😀

**Comment by florisluiten** [comment]
Dude, you're quick. 

You're welcome, glad to help

**Comment by edent** [comment]
There's a bug on the radius tool - it keeps adding the label multiple times. Happening on Firefox on Android, haven't checked other browsers yet.

**Comment by florisluiten** [comment]
Ah yes, you are right. I'm fixing that right away

**Comment by edent** [comment]
Sorry, had to revert this for two reasons.

1. On mobile, it lead to inconsistent icon sizes on the main page.
2. The radius tool was still adding extra titles.

I think it is a good idea - just need to work out how to do it properly.

**Comment by florisluiten** [comment]
You are right, we have to do it correctly.

1. I don't fully understand what you mean. Are you talking about the radius.html or README.md?
2. I seem to have made a mistake in this PR. The other PR #83 was merged and should add the label only once on radius.html. That seems to work fine.

**Comment by edent** [comment]
Here's a screenshot of the README.  As you can see, the length of the caption influences the size of the table cell.  This means some icons display smaller than others.
screenshot_20171129-133337

**Comment by florisluiten** [comment]
I see now what you mean. It looks like I'm not able to fix this, since GitHub does not render the "<colgroup>" I've added to my version of the markdown file. It looks like we have to live with the fact that we cannot display the labels in the markdown file and keep the layout nice. I think it's more important to display the icons in the same size, so no labels in the README.md file then.

I guess that's okay though, since the radius.html file is linked from the markdown file, which does contain the labels.

**Pull request merged**
