### PR TITLE
Add Opencast logo

### PR DESCRIPTION
**Pull request by lkiesow**
This patch adds the logo of [Opencast](http://opencast.org).
This is a follow-up to pull request #92, adjusting the logo to the current style guide.

### CODE REVIEW

**Comment by edent** [comment]
Thanks! Can you please make sure it follows the guidelines at https://githaub.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md

**Comment by lkiesow** [comment]
Done. Please let me know if something is not correct.

**Comment by lkiesow** [comment]
Forgot to set the new icon size…

**Comment by baybal** [comment]
`<g fill="#4bb07b"><path d="m350 256-156-156v72l84 84-84 84v72z"/><path d="m474 256-156-156v72l84 84-84 84v72z"/></g>`

Please combine paths into one

`<path fill="#4bb07b" d="M350 256-156-156v72l84 84-84 84v72zM474 256-156-156v72l84 84-84 84v72z"/>`

**Comment by lkiesow** [comment]
@baybal, your suggested path breaks the icon:
https://data.lkiesow.de/opencast/tiny-icon.svg

If you want fewer paths, then I could also just define one path and reuse it:

```xml
<svg xmlns="http://www.w3.org/2000/svg" fill="#fff" aria-label="Opencast" role="img" viewBox="0 0 512 512">
  <rect width="512" height="512" rx="15%" fill="#fff"/>
  <defs><path id="a" fill="#4bb07b" d="m350 256-156-156v72l84 84-84 84v72z"/></defs>
  <use xlink:href="#a"/>
  <use xlink:href="#a" x="124"/>
  <use xlink:href="#a" x="-388" fill="#24425d" transform="scale(-1,1)"/>
</svg>
```

**Comment by baybal** [comment]
@lkiesow  sorry, got it wrong. The correct path is M474 256L318 100v72l84 84-84 84v72zm-124 0L194 100v72l84 84-84 84v72z

**Comment by lkiesow** [comment]
@baybal, updated the logo with your path

**Comment by edent** [comment]
Perfect, thanks!

**Pull request merged**
