### PR TITLE
Aligned to guideline, path optimized and some fixes to Apple, IBM, Samsung Internet, Email, Evernote and hopefully Airbnb

### PR DESCRIPTION
**Pull request by arturoacevedob**
All were aligned accordingly and optimized to the following percentages:

Apple - 17% and corrected color.
IBM - 39% magic was done to achieve this.
Samsung Internet - 63%
Email - 8% I’m proposing a new icon that represents generic email
branding trends.
Evernote - 12% and corrected colors and fixed contrast.

Airbnb — Second try to fix the display issues in Chrome.

Updated README with the new file sizes.

### CODE REVIEW

**Comment by edent** [comment]
(On holiday now - so won't be able to approve any changes until the new year.)

**Comment by arturoacevedob** [comment]
Okay. I've already fixed the apple filename, but what do you mean it looks weird? 

Evernote's guideline only apply for their combination mark. Their iconography colors are different. Look at iOS and Android Evernote icons for reference.

Happy holidays! I won't submit until then, no worries.

**Comment by edent** [comment]
Apple is showing as `applen.svg`

I might get a chance to look tomorrow.

**Comment by arturoacevedob** [comment]
Alright.

**Pull request merged**
