### PR TITLE
 Vegetarian Logo Update #813

### PR DESCRIPTION
**Pull request by maxwithbug**
solve Vegetarian Logo Update #813

### CODE REVIEW

**Comment by Eiim** [comment]
This is pretty close! Pay attention to [CONTRIBUTING.md](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md) - in particular, the start of the SVG was changed so it no longer matches the required format, which also affects the size of the image. The background should also be white rather than transparent. It also comes in just over 1,024 bytes, so you might need to make some small optimizations. Thanks!

**Comment by maxwithbug** [comment]
@Eiim updated that, can you review it, please

**Comment by Eiim** [comment]
It's still not quite there. I'm looking for these lines:

```svg
<svg xmlns="http://www.w3.org/2000/svg"
aria-label="..." role="img"
viewBox="0 0 512 512"><path
d="m0 0H512V512H0"
fill="#fff"/> ... </svg>
```

Also, I think you accidentally edited the Vagrant logo, please remove those changes.

**Comment by edent** [comment]
Fixed in https://github.com/edent/SuperTinyIcons/commit/4a370ee39d442391dcde287a1103c7a7aafecb5f

**Pull request closed without merging**
