### PR TITLE
Add geeks for geeks logo

### PR DESCRIPTION
**Pull request by ohmschrodinger**

### CODE REVIEW

**Comment by Eiim** [comment]
A few comments:

* Your logo doesn't follow the SVG layout provided in CONTRIBUTING.md:
```svg
<svg xmlns="http://www.w3.org/2000/svg"
aria-label="..." role="img"
viewBox="0 0 512 512"><path
d="m0 0H512V512H0"
fill="#fff"/> ... </svg>
```

* You shouldn't update CONTRIBUTING.md to mark off what you've done - just use it as a guide

* I'm not sure what the reason for the change in the Python script is - if something needs changed there, it should be in a separate pull request, otherwise you don't need to touch it.

**Comment by ohmschrodinger** [comment]
Okay ill update the svg layout

About python script-
Screenshot 2024-10-02 075831
this is the error im getting with the original script

**Comment by ohmschrodinger** [comment]
Could you please share the reason for the spam label on this PR? I’d like to improve my contributions. Thank you!

**Comment by ohmschrodinger** [comment]
I understand, thanks for the clarification. I'm still working on the logo. The file size I have right now is 1.6KB, and I'm working to reduce it to 1KB as per the project guidelines.

**Comment by edent** [comment]
I've removed the spam label. Feel free to discuss your logo in the issues.

**Comment by ohmschrodinger** [comment]
Thank you! I'll send a PR as soon as the task is finished

**Pull request closed without merging**
