### PR TITLE
Resolves issue #282: Created and added iheartradio svg

### PR DESCRIPTION
**Pull request by HenrySabio**
Created and added iheart radio svg using official art files provided by iheart radio - converted eps to svg

### CODE REVIEW

**Comment by romain-dartigues** [comment]
Please follow the [contributing guide](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md) (file must be under 1 KiB, edit README.md, etc.).

**Comment by HenrySabio** [comment]
@romain-dartigues apologies.
I uploaded the wrong file but I also admit I neglected to proper ready the contributing guide.

Small concern: My smallest possible SVG created for this was 2,225 bytes (2.2kb).
Upon further research other people who have attempted the same for this logo have only been able to reduce to the same exact size. With gzip compression it can only be brought to about 1.18kb.

I know this does not align with the goal of this project so I'm afraid I'm unable to complete this.
If it's possible at all.

**Comment by edent** [comment]
How about just the red heart logo? Remove the text at the bottom. I reckon that will fit into the size limit.

**Comment by HenrySabio** [comment]
@edent that sounds great. 
I’ll do that and update the remaining files as per the contribution guidelines today!

Thank you.

**Comment by HenrySabio** [comment]
Alright @edent that reduced it by a tad over 50% and then added to reference and read me as per contribution guidelines.

**Comment by edent** [comment]
This seems to have removed the actual icon you're trying to submit.

**Comment by jmb** [comment]
I had a little go at this by chopping it in half and using a transform to mirror... Down to 1385 bytes... https://github.com/jmb/SuperTinyIcons/blob/iheartradio/images/reference/iheartradio.svg 

I thought I'd made if fit the guidelines too, but that still needs tweaking it seems!

**Comment by jmb** [comment]
Fixed the transform, tried rounding and now down to 948 bytes... :) Will do a PR to your repo @HenrySabio then you can PR to the master if you like!

**Comment by HenrySabio** [comment]
That sounds good. 
I was able to get it down to a similar size but it would not longer open in illustrator when I tried rounding the numbers. It would open  and preview fine everywhere else but would open as a blank canvas otherwise in illustrator. 

Hopefully this version works fine.

**Comment by jmb** [comment]
Yeah it's a bit tricky - I'm using Inkscape 1.0 and ended up just copy and pasting the SVG data as required!

**Comment by HenrySabio** [comment]
@jmb this looks perfect! If you could just also update the needed associated files in the reference & readme and we should be good to go with a final commit

**Comment by jmb** [comment]
I thought you could do that in your branch! ;)

Can do it in a bit if you need me to though!

**Comment by HenrySabio** [comment]
@jmb I can! I just won't be able to until later tonight. I figured the issue/pr has been open for long enough I'm sure they'd like this resolved asap. But No problem! I'll have this taken care of.

@edent Looks like We have the solution - I'll tag you when the final commit has been made and ready to merge!

**Comment by jmb** [comment]
Ok, no prob will take a look shortly.

**Comment by edent** [comment]
Teamwork makes the dream work :-)

Tag me when it's ready to go!

**Pull request merged**
