### PR TITLE
conformed XMPP logo addition

### PR DESCRIPTION
**Pull request by wuxmedia**
finally.

### CODE REVIEW

**Comment by edent** [comment]
It is really *really* close!  One last tweak, I promise!  Oh, and it is my fault - not yours.

If you set the `rx="50%"` you'll see that the logo goes outside the bounds. 

I've put guidelines on https://github.com/edent/SuperTinyIcons#guidelines - but they're not in contributing. That's my bad and I'll fix it.

**Comment by wuxmedia** [comment]
ok i've updated my version which fits. do i burn this PR or will it merge?

**Comment by edent** [comment]
Hahaha! You've earned that shirt :-)

**Comment by Neustradamus** [comment]
@wuxmedia, @edent: I am not sure that you use the good logo version...

Can you look the good one?
- https://commons.wikimedia.org/wiki/File:XMPP_logo.svg
- https://commons.wikimedia.org/wiki/File:XMPP_logo_(without_text).svg

**Comment by kuubeu** [comment]
@Neustradamus Do you mean the gradient or the text?

**Comment by Neustradamus** [comment]
@kuubeu: Old version, there was a problem:
- https://i.ibb.co/vcqmc8b/xmpp-logo-xsf-test.png

**Pull request merged**
