### PR TITLE
Adds C++ icon as submitted by @kareldonk

### PR DESCRIPTION
**Pull request by btrem**
cplusplus.svg icon created by @kareldonk and
submitted as a zip file in issue #472. Format
corrected by @btrem to match other files in repo.
Also adds reference image and updates .md files.

NB: after correcting format, the svg file is over
the 1kB limit. I'm nearly done reducing the size.

### CODE REVIEW

**Comment by kareldonk** [comment]
Probably the extra line breaks that were added contribute to the size.

**Comment by btrem** [comment]
@kareldonk yes the line breaks caused the size increase. That format is the one that mandated by @edent, see [the contributing guidelines](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md).

**Comment by edent** [comment]
Fab!

**Comment by kareldonk** [comment]
Thanks!!

**Pull request merged**
