### PR TITLE
feat: add OnlyFans

### LINKED ISSUE #853: Add OnlyFans icon
## The icon I want is:
* Name: OnlyFans
* URL: https://onlyfans.com/
* Link to icon: https://upload.wikimedia.org/wikipedia/commons/1/16/OnlyFans_logo.svg

* Vector version of the logo:he link provided above leads to the SVG version of the official logo.
* Official style guide or brand guide: OnlyFans does not have an explicitly available public brand guide, but the official logo can be found and referenced via the Wikipedia page

### PR DESCRIPTION
**Pull request by SirMonteiro**
Thank you for your contribution!  Before sending this Pull Request, please confirm the following:

* [x] You have read [the contributing guidelines](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md)
* [x] The icon's size is *under* 1,024 Bytes
* [x] The layout of the SVG looks like this including newlines
```svg
<svg xmlns="http://www.w3.org/2000/svg"
aria-label="..." role="img"
viewBox="0 0 512 512"><path
d="m0 0H512V512H0"
fill="#fff"/> ... </svg>
```

If you have done the above, please send the Pull Request.
Closes #853

### CODE REVIEW

**Comment by edent** [comment]
This looks a bit off-centre to me. Or am I wrong?

**Comment by SirMonteiro** [comment]
I tried to fit the entire icon into green and yellow zones from guidelines, but centering it looks better.

**Comment by Eiim** [comment]
It's effectively centered (technically a half-pixel off), but arguably looks uncentered because the visual weight of the logo is skewed to the left. It's subjective but I think it looks fine as it is.

**Comment by edent** [comment]
Looks good! Could you please make sure it fits the formatting template, then I'll merge it. Thanks :-)

**Comment by SirMonteiro** [comment]
The border hits the yellow mark, but it fits all requirements!

**Comment by edent** [comment]
@SirMonteiro sorry - I meant the line-breaks within the SVG file.

**Pull request merged**
