### PR TITLE
adds Numero Group logo

### PR DESCRIPTION
**Pull request by btrem**

### CODE REVIEW

**Comment by edent** [comment]
This is missing an ARIA description. But, I'm not really sure this is prominent enough to warrant inclusion. Do lots of people use this icon on their websites?

**Comment by btrem** [comment]
> This is missing an ARIA description.

Fixed.

> But, I'm not really sure this is prominent enough to warrant inclusion. Do lots of people use this icon on their websites?

Hmm, I dunno. I did wonder what the bar is. The project README says a submitted icon must "represent a popular service's current logo." But what constitutes "popular?" There are many icons in the repo for companies I've never heard of (Zorino? Briar? Uphold? Orcid? etc.)

I'll concede that Numero, which is an independent record label, is probably not a household name. Your call. If you decide not to merge, I'll understand.

**Comment by btrem** [comment]
@edent I'll let you close this if you decide not to merge. And as I said, perfectly understandable. Next time, I'll ask before putting the work in. Honestly, I'm never sure -- in general, not just for this repo -- which is better:
- open an issue, than do the work, then create a PR to resolve the issue; or
- just do the work and create the PR

I won't delete the branch until you've decided.

**Comment by edent** [comment]
Sorry for the delay. I think, in general, best to check before putting the effort in. Love the other submission though.

**Comment by btrem** [comment]
> Sorry for the delay. I think, in general, best to check before putting the effort in.

No problem, I understand. And yes, next time I'll check first. (I had already done the work in #790 when your reply in this issue reached me. So I didn't check on that one, but I will in the future, especially for something that is only tangentially related to this project.)

**Pull request closed without merging**
