### PR TITLE
Add Blender logo (849 bytes)

### PR DESCRIPTION
**Pull request by MalloryA**

### CODE REVIEW

**Comment by Eiim** [comment]
The logo looks like it's been stretched. Also, there's a jump in the orange part.

**Comment by MalloryA** [comment]
I can see the jumps if I blow it up really big. I'll see if I can fix those.

In what way does it look stretched? Like it's too wide, too tall?

**Comment by MalloryA** [comment]
Fixed the three little jumps 👍

**Comment by Eiim** [comment]
Looks good! Doesn't look stretched to me anymore, not sure what I was seeing. Please follow the file template in CONTRIBUTING.md though.

**Comment by MalloryA** [comment]
> Please follow the file template in CONTRIBUTING.md though.

Sure. What did I miss? I've got the ARIA attributes, I've got the white square with rounded corners. I rechecked the alignment with the green and yellow circles and I moved it a little further towards the center.

**Comment by Eiim** [comment]
There should be newlines in the <svg> tag. I'm not sure why, but that's the standard that was set. Thanks!

**Comment by MalloryA** [comment]
Sure thing 👍

**Comment by kuubeu** [comment]
Hi, the standard formatting in this repository (mentioned in [CONTRIBUTING.md](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md#new-file)) is as follows:
```svg
<svg xmlns="http://www.w3.org/2000/svg"
aria-label="..." role="img"
viewBox="0 0 512 512"><rect
width="512" height="512"
rx="15%"
fill="#fff"/>...</svg>
```
in that order, everything else being in a single line in place of the ellipsis. There are some exceptions to this rule, but they don't apply in this case

**Comment by MalloryA** [comment]
Ohh, I see what you mean now. Thanks. Done 👍

**Comment by edent** [comment]
Looks brilliant. Thanks.

Re:
> There should be newlines in the tag. I'm not sure why, but that's the standard that was set.

I set it that way to make it easier to view diffs.

**Pull request merged**
