### PR TITLE
Gmail and Google Play Logos

### PR DESCRIPTION
**Pull request by tonyraoul**
add gmail and google play logos

### CODE REVIEW

**Comment by edent** [comment]
Thanks Tony!  The GMail one looks broken in the preview - any way of fixing that?

gmail

**Comment by arturoacevedob** [comment]
@tonyraoul How did you fix the Chrome issue?

**Comment by tonyraoul** [comment]
it is all about floating points , I was to aggressive removing floating points I just restored few of them until it is back in shape

**Comment by arturoacevedob** [comment]
Thanks for the response!

**Pull request merged**
