### PR TITLE
Add Misskey

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
Should adhere to all guidelines, added everything except Android version.  758 bytes.

Misskey's official logo is currently not super strict on coloring or formatting (see readme versus assets versus github icon versus misskey hub, etc...)

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
@Eiim I should add that Misskey is another SNS on ActivityPub, much like Mastodon/PixelFed/Friendica but has many of its own unique features.

**Comment by Eiim** [comment]
The icon extends into the red zone of the reference image, could you shrink it a bit? Also, the last newline in the SVG isn't necessary :)

image

**Comment by ThatOneCalculator** [comment]
I tried editing it but it came out to 1.4kb... do you think you could help?

```
<svg xmlns="http://www.w3.org/2000/svg"
aria-label="Misskey" role="img"
viewBox="0 0 512 512"><rect
width="512" height="512"
rx="15%"
fill="#fff"/>
<path d="m211.19 325.88c-15.217 0-28.744-8.4541-34.662-19.444-3.3816-4.227-9.2995-5.9179-9.2995 0v29.589c0 10.99-4.227 21.135-12.681 29.589a41.425 41.425 0 0 1-30.435 12.681c-11.836 0-21.981-4.2271-30.435-12.681a42.271 42.271 0 0 1-12.681-29.589v-159.78c0-9.2995 2.5362-17.754 7.6087-24.517a41.425 41.425 0 0 1 35.507-18.599c12.681 0 23.672 5.0725 32.126 15.217l43.961 50.725c0.84542 0.8454 4.227 6.7633 10.99 6.7633 6.7633 0 10.145-5.9179 10.99-6.7633l43.116-50.725a42.271 42.271 0 0 1 47.343-12.681c8.4541 3.3817 15.217 8.4541 20.29 16.063 5.9179 6.7633 8.4541 15.217 8.4541 24.517v159.78c0 10.99-4.227 21.135-12.681 29.589a41.425 41.425 0 0 1-30.435 12.681 42.271 42.271 0 0 1-43.116-43.116v-28.744c0-7.6087-7.6087-2.5362-10.145 0a38.043 38.043 0 0 1-33.816 19.444zm182.61-119.2a36.353 36.353 0 0 1-37.198-36.353c0-10.145 3.3816-19.444 10.99-26.208 6.7633-6.7633 16.063-10.99 26.208-10.99 10.145 0 18.599 3.3816 26.208 10.99 6.7633 6.7633 10.99 16.063 10.99 26.208a36.353 36.353 0 0 1-37.198 36.353zm0 7.6087c10.145 0 18.599 3.3816 26.208 10.99 6.7633 6.7633 10.99 16.063 10.99 26.208v89.614c0 10.145-4.2271 19.444-10.99 26.208a35.507 35.507 0 0 1-26.208 10.99 36.353 36.353 0 0 1-37.198-37.198v-89.614c0-10.145 3.3816-19.444 10.99-26.208 7.6087-7.6087 16.063-10.99 26.208-10.99z" fill="#86b300" stroke-width=".84541"/></svg>
```

**Comment by PaulCapron** [comment]
You can try [SVGO](https://github.com/svg/svgo), or a web interface to it, SVGOMG: https://jakearchibald.github.io/svgomg/, to shrink the image.
The main `<path>`, shrinked but without visibly altering it, would become:
```svg
<path d="M211.2 325.9a39.8 39.8 0 0 1-34.7-19.5c-3.4-4.2-9.3-5.9-9.3 0V336a41 41 0 0 1-12.7 29.6 41.4 41.4 0 0 1-30.4 12.7c-11.8 0-22-4.2-30.4-12.7A42.3 42.3 0 0 1 81 336V176.2c0-9.3 2.5-17.7 7.6-24.5a41.4 41.4 0 0 1 35.5-18.6c12.7 0 23.7 5.1 32.1 15.2l44 50.8c.8.8 4.2 6.7 11 6.7s10.1-5.9 11-6.7l43.1-50.8a42.3 42.3 0 0 1 47.3-12.6 42.3 42.3 0 0 1 20.3 16c6 6.8 8.5 15.2 8.5 24.5V336a41 41 0 0 1-12.7 29.6 41.4 41.4 0 0 1-30.4 12.7 42.3 42.3 0 0 1-43.1-43.1v-28.8c0-7.6-7.7-2.5-10.2 0a38 38 0 0 1-33.8 19.5zm182.6-119.2a36.4 36.4 0 0 1-37.2-36.4c0-10.1 3.4-19.4 11-26.2a37 37 0 0 1 26.2-11c10.1 0 18.6 3.4 26.2 11a37 37 0 0 1 11 26.2 36.4 36.4 0 0 1-37.2 36.4zm0 7.6c10.1 0 18.6 3.4 26.2 11a37 37 0 0 1 11 26.2V341a37 37 0 0 1-11 26.2 35.5 35.5 0 0 1-26.2 11 36.4 36.4 0 0 1-37.2-37.2v-89.6c0-10.2 3.4-19.5 11-26.2 7.6-7.6 16-11 26.2-11z" fill="#86b300"/>
```

**Comment by Eiim** [comment]
I just finished up manually editing that path in https://yqnn.github.io/svg-path-editor/ and got the following 300-byte path data (the part that goes in the `d="`):

```
M176.5 306.5c-3.4-4.2-9.3-5.9-9.3 0v29.6a43 43 0 01-86.2 0v-159.8a43 43 0 0175.2-27.9l44 50.7a14 14 0 0022 0l43.1-50.7a43 43 0 0176.1 27.9v159.8a43 43 0 01-86.2-.8v-28.7c0-7.6-7.6-2.5-10.1 0a40 40 0 01-68.5 0zm217.3-99.8a1 1 0 010-72.8 1 1 0 010 72.8zm37.2 134.4a1 1 0 01-74.4 0v-89.6a1 1 0 0174.4 0z
```

As your original path data was 1273 bytes, that should save about a kilobyte and get you well within the limit.

**Pull request closed without merging**
