### PR TITLE
feat: :sparkles: added svg for c language

### LINKED ISSUE #719: Add C logo
## The icon I want is:

* Name: C
* URL: 
* Link to icon: https://commons.wikimedia.org/wiki/File:The_C_Programming_Language_logo.svg

* Vector version of the logo: https://commons.wikimedia.org/wiki/File:The_C_Programming_Language_logo.svg
* Official style guide or brand guide:

### PR DESCRIPTION
**Pull request by AnkurBansal18**
## what does this PR do ?
This PR introduces the SVG for C language.

Fixes #719 

##Checklist (according to CONTRIBUTING.md)
--my filename structure follows (Filename should be nameofservice.svg )
-- my icon follows and fits under icon size guidelines
-- my codes updated the readme using edit readme using python3 generate_readme_table.py
-- I have added the  reference image
-- I have edited reference page

### CODE REVIEW

**Comment by jmb** [comment]
I'm not sure if its intentional but the colours don't seem to quite match the reference image.
Also, please check the table in the readme and if you can use the python script to re-generate (see the [CONTRIBUTING.md](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md) file for details - at the moment the Swift icon cell is in an extra column all on it's own!

**Comment by AnkurBansal18** [comment]
Hey @jmb, I have updated the reference image with the exact colors as SVG. Also, I have regenerated the README using the Python script.

**Comment by jmb** [comment]
A couple more comments I'm afraid - the triangle that is on the right hand side between the two ends of the 'C' is missing and the corners between the current two coloured areas don't line up.

**Comment by AnkurBansal18** [comment]
> A couple more comments I'm afraid - the triangle that is on the right hand side between the two ends of the 'C' is missing and the corners between the current two coloured areas don't line up.

Fixed the triangle issue.

**Comment by jmb** [comment]
I think you should be matching the svg icon to the reference image (which was suggested to be the same as the C++ logo without the ++ and is on Wikimedia here: https://commons.wikimedia.org/wiki/File:C_Programming_Language.svg ) not adjusting the reference image to your svg.

You need to to make sure the svg icon fits inside the green circle on the guideline template and it has the white background (in this case). 

The easiest option would be to take the cplusplus.svg file and remove the paths that make up the ++ 😉

**Comment by jmb** [comment]
@AnkurBansal18 are you going to continue this PR?

**Comment by AnkurBansal18** [comment]
Hey, sure I will complete this by tomorrow. Was busy in some other work.

**Pull request closed without merging**
