### PR TITLE
added mastercard.svg file

### PR DESCRIPTION
**Pull request by ohmschrodinger**
Thank you for your contribution!  Before sending this Pull Request, please confirm the following:

* [x] You have read [the contributing guidelines](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md)
* [x] The icon's size is *under* 1,024 Bytes
* [x] The layout of the SVG looks like this including newlines
```svg
<svg xmlns="http://www.w3.org/2000/svg"
aria-label="..." role="img"
viewBox="0 0 512 512"><path
d="m0 0H512V512H0"
fill="#fff"/> ... </svg>
```

If you have done the above, please send the Pull Request.

#873

### CODE REVIEW

**Comment by edent** [comment]
I think you can make this even smaller. Take a look at the Flickr example for some ideas.

**Comment by ohmschrodinger** [comment]
im not able to make the 2 semicircles in orange color
heres the updated code

```
<svg xmlns="http://www.w3.org/2000/svg"
aria-label="mastercard" role="img"
viewBox="0 0 512 512">
  <path d="M0 0h512v512H0" fill="#fff"/>
  <circle cx="180" cy="256" fill="#EB001B" r="120"/>
  <circle cx="332" cy="256" fill="#F79E1B" r="120"/>
    <path d="M310 161.8H202.7v189.4h107.5V161.8h-.2Z" fill="#FF5A00"/>
</svg>
```


can you help me out?

**Comment by edent** [comment]
Have a look at http://xahlee.info/js/svg_path_ellipse_arc.html

**Comment by ohmschrodinger** [comment]
DONE THANKS!!!!
lemme commit the changes

**Comment by edent** [comment]
Excellent! Now run it through a minifier like https://svgomg.net/ to see if you can make it even smaller :-)

**Comment by ohmschrodinger** [comment]
Done!!!

**Comment by edent** [comment]
Nice one! Can you do Amex and Visa next??

**Pull request merged**
