### PR TITLE
Added Zorin OS & Netbeans logo

### PR DESCRIPTION
**Pull request by sandy3002**
@edent I added logos of zorin os and netbeans. The netbeans one looks a bit stretched, I am trying to correct this in future updates. Also tell me if anything is wrong, first open source contribution 😅.

### CODE REVIEW

**Comment by Eiim** [comment]
Both of these fill the entire frame. Take a look at [CONTRIBUTING.md](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md), they should fit within a smaller circle.

**Comment by Eiim** [comment]
Also, the Zorin logo doesn't follow the template and includes some extra Inkscape metadata.

**Comment by sandy3002** [comment]
Ok, I am trying to correct these

**Comment by sandy3002** [comment]
@Eiim Kindly check the updated files. Thank you

**Comment by Eiim** [comment]
Sorry it took so long to get back to this. Looking much better! Only one thing, is it possible to use `fill="#abcedf"` instead of `style="fill:#abcdef"`? That's just a small optimization that jumped out to me.

**Comment by sandy3002** [comment]
Done! Take a look

**Comment by Eiim** [comment]
Please update the file sizes in the README as well.

**Comment by sandy3002** [comment]
Completed

**Comment by Eiim** [comment]
Thanks!

**Pull request merged**
