### PR TITLE
feat: Added matrix logo under 1024 Bytes

### PR DESCRIPTION
**Pull request by RitikPatni**
Fix for https://github.com/edent/SuperTinyIcons/issues/553

### CODE REVIEW

**Comment by Eiim** [comment]
Quick heads up, this doesn't seem to include the required template in the readme. The "m" also seems like it has an excessive number of nodes, and some commands that could be arcs rather than curves and be more efficient.

**Comment by RitikPatni** [comment]
@Eiim Hey, can you please point me to the template you're referencing. I tried looking up to your old PR's, but I'm not sure what you're trying to say here. Regarding the SVG, I'll read up on the points you suggested and will share an updated SVG

**Comment by Eiim** [comment]
@RitikPatni It's at the bottom of the README, or in CONTRIBUTING.md

**Comment by RitikPatni** [comment]
@Eiim Ok thanks found it, will update the SVG to satisfy those conditions

**Comment by edent** [comment]
This is a really good start. Please can you follow the guide in https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md

**Comment by RitikPatni** [comment]
@edent Sure I'll do it and update the PR

**Comment by edent** [comment]
As per https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md

> Use https://inloop.github.io/svg2android/ to create an Android-compatible XML file.

**Comment by RitikPatni** [comment]
@edent Updated the android image thanks for pointing out to the docs

**Comment by edent** [comment]
Fixed in #676

**Pull request closed without merging**
