### PR TITLE
Leetcode Logo

### PR DESCRIPTION
**Pull request by kycilius**
Thank you for your contribution!  Before sending this Pull Request, please confirm the following:

* [x] You have read [the contributing guidelines](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md)
* [x] The icon's size is *under* 1,024 Bytes
* [x] The layout of the SVG looks like this including newlines
```svg
<svg xmlns="http://www.w3.org/2000/svg"
aria-label="..." role="img"
viewBox="0 0 512 512"><path
d="m0 0H512V512H0"
fill="#fff"/> ... </svg>
```

If you have done the above, please send the Pull Request.

### CODE REVIEW

**Comment by edent** [comment]
OK, let's take a look at this. 

How many bytes is the image that you submitted?

Does this image look like all the other images in the directory?

**Comment by edent** [comment]
Can you describe what you have added and what you have difficulty with?

**Comment by kycilius** [comment]
i have optimised that and also adjusted the size. should I create a pull request again or it will considered as changed

**Comment by edent** [comment]
@kycilius you need to push your changes. 

This is looking good. Remember to read the Contributing guide - and make sure your icon looks like the sample code.

**Comment by kycilius** [comment]
thanks alot @edent sir

**Pull request closed without merging**
