### PR TITLE
Optimize some SVG paths

### PR DESCRIPTION
**Pull request by Yqnn**
Hi 👋 ,
I'm the maintainer  of https://github.com/Yqnn/svg-path-editor , and I recently released a new feature to optimise svg paths.
By running it on all svg paths of this repository, I managed to save few bytes.

I did a full screen manual comparison of all the modified logos to ensure nothing changed (allowing to find few bugs in the optimizer :) )

Here are the details:
<table>
<tr><th>File</th><th width="130">Bytes saved</th></tr>
<tr><td>baidu.svg, bitbucket.svg, blender.svg, bluesky.svg, brave.svg, bun.svg, citrix_compact.svg, clojure.svg, coil.svg, colaboratory.svg, deezer.svg, dropbox.svg, email.svg, espressif.svg, ethereum.svg, flattr.svg, gandi.svg, go.svg, goodreads.svg, google_calendar.svg, google_drive.svg, google_maps.svg, google_meet.svg, google_scholar.svg, h-card.svg, jsonfeed.svg, lastpass.svg, lock.svg, malt.svg, minecraft.svg, netbeans.svg, openbugbounty.svg, openstreetmap.svg, opera.svg, plex.svg, protonmail.svg, signal.svg, snapchat.svg, square_cash.svg, stumbleupon.svg, svelte.svg, tox.svg, vagrant.svg, venmo.svg, whatsapp.svg</td><td>1</td></tr>
<tr><td>arch_linux.svg, citrix.svg, digidentity.svg, ea.svg, endeavouros.svg, firefox.svg, flutter.svg, git.svg, gitea.svg, gmail_old.svg, google.svg, google_collaborative_content_tools.svg, google_docs_editors.svg, google_plus.svg, h-entry.svg, html5.svg, logitech.svg, mailchimp.svg, nhs.svg, nodejs.svg, olympics.svg, opencores.svg, phone.svg, pinboard.svg, quora.svg, stackoverflow.svg, strava.svg, ubuntu.svg, udemy.svg, x.svg</td><td>2</td></tr>
<tr><td>angellist.svg, authy.svg, buffer.svg, dart.svg, floatplane.svg, google_maps_old.svg, intercom.svg, itch_io.svg, ok.svg, pinterest.svg, pixelfed.svg, popos.svg, rubygems.svg, svg.svg, symantec.svg, telegram.svg, ubiquiti.svg, yarn.svg, youtube.svg</td><td>3</td></tr>
<tr><td>acast.svg, briar.svg, ebay.svg, edge.svg, gmail.svg, kodi.svg, linux_mint.svg, outlook.svg, raspberry_pi.svg, skype.svg, terraform.svg, tiktok.svg, uphold.svg, vimeo.svg</td><td>4</td></tr>
<tr><td>apereo.svg, auth0.svg, behance.svg, discord.svg, hackerone.svg, homekit.svg, imdb.svg, macos.svg, roundcube.svg, sentry.svg, taiga.svg, upwork.svg, wikipedia.svg</td><td>5</td></tr>
<tr><td>azure.svg, coffeescript.svg, element.svg, keskonfai.svg, liberapay.svg, mail.svg, react.svg, tripadvisor.svg, viber.svg, wifi.svg</td><td>6</td></tr>
<tr><td>apple_podcasts.svg, cloudflare.svg, hulu.svg, meetup.svg, paypal.svg, php.svg, rust.svg, stackexchange.svg, wireguard.svg</td><td>7</td></tr>
<tr><td>finder.svg, friendica.svg, mastodon.svg, origin.svg, safari.svg, uber.svg, webassembly.svg</td><td>8</td></tr>
<tr><td>ko-fi.svg, line.svg, pdf.svg, swift.svg</td><td>9</td></tr>
<tr><td>bugcrowd.svg, freecodecamp.svg, hp.svg, thisamericanlife.svg, ubisoft.svg, uplay.svg, vim.svg, webtoons.svg</td><td>10</td></tr>
<tr><td>humblebundle.svg, ibm.svg, qq.svg, samsung_swoop.svg, semaphoreci.svg</td><td>11</td></tr>
<tr><td>pornhub.svg, sass.svg, sogo.svg</td><td>12</td></tr>
<tr><td>cplusplus.svg, github.svg, rubyonrails.svg, visualstudiocode.svg</td><td>13</td></tr>
<tr><td>coinpot.svg, lobsters.svg, overcast.svg</td><td>14</td></tr>
<tr><td>guacamole.svg, justgiving.svg, matrix.svg</td><td>15</td></tr>
<tr><td>json-ld.svg, markdown.svg</td><td>16</td></tr>
<tr><td>dev_to.svg</td><td>17</td></tr>
<tr><td>todoist.svg</td><td>18</td></tr>
<tr><td>elastic.svg, vlc.svg, wechat.svg</td><td>19</td></tr>
<tr><td>itunes_podcasts.svg</td><td>20</td></tr>
<tr><td>gradle.svg</td><td>21</td></tr>
<tr><td>duckduckgo.svg</td><td>22</td></tr>
<tr><td>guilded.svg, tunein.svg</td><td>23</td></tr>
<tr><td>samsung.svg</td><td>27</td></tr>
<tr><td>internet_archive.svg</td><td>31</td></tr>
<tr><td>researchgate.svg</td><td>32</td></tr>
<tr><td>java.svg, tutanota.svg</td><td>39</td></tr>
<tr><td>freebsd.svg</td><td>41</td></tr>
<tr><td>drupal.svg</td><td>42</td></tr>
<tr><td>iheartradio.svg</td><td>61</td></tr>
<tr><th>total</th><td>1353</td></tr>
</table>

### CODE REVIEW

**Comment by edent** [comment]
Could you please give a little explanation about what you've done, how you've done it, and the tools you've used?

Thanks 😃

**Comment by Yqnn** [comment]
I guess I will have to update the README too, I should be able to do it tomorrow.

**Comment by Eiim** [comment]
From some spot checks, this looks pretty good. I see some basic stuff that the tool already did with minify output (eg removing unnecessary whitespace/commands) but also some more tricky stuff, like changing the path start (which can be powerful but really annoying, I even built my own [buggy tool](https://github.com/Eiim/SVGPathStartMover) to help with it) and smarter relative/absolute choices. Nicely done! Out of curiosity, where's the new optimization feature in the editor? I love the tool but I'm not noticing a new button there or anything.

**Comment by Yqnn** [comment]
There are 2 new buttons here:
image
If you don't see them, just wait few seconds and refresh the page, they should appear.

In addition to the standard minification (that doesn't change the path), the Optimize function can:
- Reverse the path
- Use relative or absolute coordinates
- Tranform sequences `M M` > `M`, `Z Z`>`M` and `Z M`>`Z`
- Remove useless `L`, `V` or `H`
- Perform automatic conversions to `H`, `V`, `T` or `S`
Changing the origin is not supported.
There is also `M Z`>`M` conversion, but it's disabled, because it breaks paths relying on `stroke-linecap="round"` (like [vivino.svg](https://github.com/edent/SuperTinyIcons/blob/master/images/svg/vivino.svg) ).

**Comment by Eiim** [comment]
Ah, indeed. I was looking at Bluesky and thought I saw the start being different, but it was actually reversed.

**Comment by edent** [comment]
That's brilliant - thanks!

**Comment by edent** [comment]
@Yqnn I'm granting you commit access to the Repo.  This is per the advice of [The Pull Request Hack](https://felixge.de/2013/03/11/the-pull-request-hack.html).

Please use this new power wisely :-)

**Pull request merged**
