### PR TITLE
Tailwind icon added 

### PR DESCRIPTION
**Pull request by Shailsharma2604**
Thank you for your contribution!  Before sending this Pull Request, please confirm the following:

* [x] You have read [the contributing guidelines](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md)
* [x] The icon's size is *under* 1,024 Bytes
* [x] The layout of the SVG looks like this including newlines
```svg
<svg xmlns="http://www.w3.org/2000/svg"
aria-label="..." role="img"
viewBox="0 0 512 512"><path
d="m0 0H512V512H0"
fill="#fff"/> ... </svg>
```

If you have done the above, please send the Pull Request.

### CODE REVIEW

**Comment by Shailsharma2604** [comment]
Can you tell what I spam ??

**Comment by edent** [comment]
@Shailsharma2604 You checked the box saying "The icon's size is under 1,024 Bytes" - what size is the icon you submitted?

You checked the box saying you'd follow the SVG guidance. Did you submit an SVG?

This appears to be Hacktoberfest spam. If I am wrong, please let me know.

**Comment by Shailsharma2604** [comment]
> @Shailsharma2604 You checked the box saying "The icon's size is under 1,024 Bytes" - what size is the icon you submitted?
> 
> You checked the box saying you'd follow the SVG guidance. Did you submit an SVG?
> 
> This appears to be Hacktoberfest spam. If I am wrong, please let me know.

See as I am new to this so only it happened 
It's not spam

**Comment by edent** [comment]
@Shailsharma2604 your are not new. Your GitHub account was created in 2023.

We have a Contributing Guidelines document.  It is important that you read what a project wants.

You cannot just add anything you feel like.

We try to be a welcoming community. You should read the guidelines and then ask questions.

I've given you the spam label so you will not get Hacktoberfest recognition for this bad contribution.

**Pull request closed without merging**
