### PR TITLE
Visa Logo

### PR DESCRIPTION
**Pull request by ohmschrodinger**
Thank you for your contribution!  Before sending this Pull Request, please confirm the following:

* [x] You have read [the contributing guidelines](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md)
* [x] The icon's size is *under* 1,024 Bytes
* [x] The layout of the SVG looks like this including newlines
```svg
<svg xmlns="http://www.w3.org/2000/svg"
aria-label="..." role="img"
viewBox="0 0 512 512"><path
d="m0 0H512V512H0"
fill="#fff"/> ... </svg>
```

If you have done the above, please send the Pull Request.

#875

### CODE REVIEW

**Comment by edent** [comment]
I don't think the orange swoosh is used any more - see https://www.merchantsignage.visa.com/brand_guidelines

Don't forget to run it through SVG OMG or similar to shrink the paths.

**Comment by ohmschrodinger** [comment]
Done!

**Comment by edent** [comment]
Please can you replace the reference image with the one from the brand guidelines website. Also, replace the URl with the brand guidelines one.

The point of the reference image is to see how our SVG compares to the *official* logo.

**Comment by ohmschrodinger** [comment]
Sure thing!

**Pull request merged**
