### PR TITLE
Add Opencast Logo

### PR DESCRIPTION
**Pull request by lkiesow**
This patch adds the logo of [Opencast](http://opencast.org)

### CODE REVIEW

**Comment by lkiesow** [comment]
Merge conflicts fixed

**Comment by lkiesow** [comment]
Hi @edent,
I'm wondering why you declined this without any comment.
Could you give a short explanation for why you declined this pull request?

**Comment by edent** [comment]
Sorry, my mobile client ate the comment I sent.

This currently doesn't fit within the style guidelines. If you can make it align with the others - and add the necessary stuff to the reference documentation, I'm happy to accept it.

**Comment by lkiesow** [comment]
Ok, thanks for letting me know. I've noticed the new style guides but had no time so far to fix the icon. Will do and create a new pull request.

**Pull request closed without merging**
