### PR TITLE
added-graphql-logo

### PR DESCRIPTION
**Pull request by Karan-Nagure**
I have taken care of each and every constraints. I have added the logo of GraphQL.  Issue no. #828

### CODE REVIEW

**Comment by edent** [comment]
Do you think this looks right?

image

Would you like to try and fix it, or shall I just apply the Hacktoberfest spam label now?

**Comment by Karan-Nagure** [comment]
Sir, please check out the changes I have did in the 2nd commit. I have uploaded the correct svg file now. Please do check and merge it if it is correct.
Screenshot 2024-10-27 122014

**Comment by edent** [comment]
Did you read https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md ?

Do you think this complies with the information in there?

**Comment by Karan-Nagure** [comment]
Yes, I think everything is okay except creating a android version

**Comment by edent** [comment]
Your logo is *over* 1,024 bytes. It doesn't look like the others. You've added the R logo into the root. For some reason, you've also added an HTML5 logo.

I don't know if you're trying to complete Hacktoberfest - but this isn't the way to do it.

Don't just add loads of AI generated stuff you don't understand. Read the guidelines. Ask questions. Start small.

**Pull request closed without merging**
