### PR TITLE
Tweak GitHub logo

### PR DESCRIPTION
**Pull request by ace-dent**
Small improvements to best match the official GitHub brand mark.
- Fix Octocat’s tentacle - not quite thick enough.
   Minimal geometry changes made with ‘Yqnn/svg-path-editor’, no change in file size.
- Correct background colour to better match official vector artwork.

### CODE REVIEW

**Comment by ace-dent** [comment]
Comparing current artwork to official vector files, shows that the tentacle needed tweaking.

Affinity_Designer_-_github_svg__Modified___100_0__

**Comment by ace-dent** [comment]
From checking GitHub brand guidelines, there doesn't seem to be a background colour explicitly given.

Inspecting the official `.png` bitmap images gives:
#171516 - RGB(23, 21, 22)

Whereas, the official vector artwork (`.ai` and `.eps`) gives:
#181717 - RGB(24, 23, 23)

Currently we have (changed by #112):
#1B1817 - RGB(27, 24, 23)

Originally we used:
#171515 - RGB(23, 21, 21) ... which is closer.

This PR applies the vector artwork colours, as presumably this best matches the design intent.
--> #181717 - RGB(24, 23, 23)
(In reality, this is barely visible to most users).

**Comment by ace-dent** [comment]
Updated PNG reference image and Android VectorDrawable.
... Hoping for a Gold Star ;-)

**Comment by edent** [comment]
🌟🌟🌟🌟🌟

**Pull request merged**
