### PR TITLE
Add icon for researchgate.net

### PR DESCRIPTION
**Pull request by LinusU**
https://www.researchgate.net

### CODE REVIEW

**Comment by edent** [comment]
Cheers! Do you have a higher resolution version of the reference image? The G doesn't look quite right to me.

Thanks for the contribution 😁

**Comment by edent** [comment]
Looks like there's a better one at https://mobile.twitter.com/ResearchGate/photo

**Comment by LinusU** [comment]
That's a great find!

Do you have any tips for tracing the outlines? Are you using any tools?

The current version was made by importing it in inkscape and putting out two text elements 🙈 I then tried to match the font and size best I could, but it's far from perfect...

**Comment by edent** [comment]
That's pretty much what I do ☺️

**Comment by LinusU** [comment]
Found an amazing tool, new file incoming 🐎 

https://www.vectorizer.io/

**Comment by LinusU** [comment]
Updated 👏

**Comment by LinusU** [comment]
> Typo in the aria label

✅ 

> Please can you make sure the viewbox is 512x512

Hmm, either the file will be larger (because I need to introduce fractions) or quality will degrade a bit...

I tried resizing it and keeping the round nice numbers, but that doesn't look as good, you can absolutely notice...

```
1,079 images/svg/researchgate 512-0.svg (looks bad)
1,561 images/svg/researchgate 512-1.svg (looks good)
1,287 images/svg/researchgate 4000.svg  (looks perfect)
```

**Comment by LinusU** [comment]
@edent just let me know how to proceed, happy to pick any of the files ☺️

**Comment by edent** [comment]
I'm travelling at the moment - and GitHub's mobile tools are crap. It has to fit in the template in the readme, and be under 1,024 bytes.

**Comment by LinusU** [comment]
> Under 1KB each!

Ah, just saw this, will try crunching it a bit more 😬

**Comment by LinusU** [comment]
Awesome, thanks 👍

**Pull request merged**
