### PR TITLE
Add markdown icon

### PR DESCRIPTION
**Pull request by hirakJS**

### CODE REVIEW

**Comment by edent** [comment]
Could you please make this fit in with the other icons? It should fit within a circle.  You can also shrink the size by simplifying the transform.

**Comment by hirakJS** [comment]
will do the fix.

**Comment by hirakJS** [comment]
Changes done. Please have a look.

**Comment by edent** [comment]
Excellent work! Add it to the README and I'll merge.

**Comment by hirakJS** [comment]
I've added the changes. You can merge now.

**Comment by hirakJS** [comment]
Please let me know if you want any changes.

**Pull request merged**
