### PR TITLE
Fixed luckyframework alignment and smoothed edges (also half the size)

### PR DESCRIPTION
**Pull request by vangyyy**
Much smaller icon
Smoother and aligned edges

### CODE REVIEW

**Comment by vangyyy** [comment]
Android drawable already fixed in #300.

**Comment by edent** [comment]
Think you've included the wrong file in this commit. The SVG looks like an Inkscape export.

**Comment by edent** [comment]
Thanks. Just to note, I've added a space into the ARIA label. That's so screen readers can pronounce it properly. I think there are a few already in the repo I need to correct.

**Comment by vangyyy** [comment]
Yes, I looked at one and it didn't have space, so I didn't use one also. When I find some missing spaces in the future, I'll fix them.

**Pull request merged**
