### PR TITLE
Add javascript icon

### PR DESCRIPTION
**Pull request by hirakJS**

### CODE REVIEW

**Comment by edent** [comment]
This looks great! Could I please ask you to make one small change?

Take a look at [the guidelines](https://github.com/edent/SuperTinyIcons#guidelines).  When the corner radius is at 50%, the "JS" overlaps the background. So I think you should move the JS slightly closer to the centre.

Thanks!

**Comment by hirakJS** [comment]
I'll do the changes

**Comment by hirakJS** [comment]
> This looks great! Could I please ask you to make one small change?
> 
> Take a look at [the guidelines](https://github.com/edent/SuperTinyIcons#guidelines). When the corner radius is at 50%, the "JS" overlaps the background. So I think you should move the JS slightly closer to the centre.
> 
> Thanks!

done

**Comment by edent** [comment]
Brilliant! Thank you :-)

**Pull request merged**
